# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: /plugins/october/blog/models/post/list_columns.yaml

# Model Class name
model-class: Plugins\October\Blog\Models\Post

# List Title
title: Manage Blog Posts

# Link URL for each record
record-url: october/blog/posts/update/:id

# Message to display if the list is empty
no-records-message: backend::lang.list.no_records

# Records to display per page
records-per-page: 5

# Display checkboxes next to each record
show-checkboxes: yes

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



